server:
  port: 9090
  ssl:
    key-store: file:///C:\Workspace\cert\mykeys.jks
    key-store-password: mokukin
    key-password: mokukin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud?useUpomnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: moku
    password: M@kuk2n!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    schema:
      - classpath:sql/order-schema.sql
      - classpath:sql/ingredient-schema.sql
      - classpath:sql/taco-schema.sql
    data:
      - classpath:sql/ingredients.sql
    #; 为sql脚本中语句分隔符
    separator: ;
    #utf-8 为文件的编码
    sql-script-encoding: utf-8
    #always为始终执行初始化，embedded只初始化内存数据库（默认值）,如h2等，never为不执行初始化。
    initialize: true
    initialization-mode: never
    #遇到语句错误时是否继续，若已经执行过某些语句，再执行可能会报错，可以忽略，不会影响程序启动
    continue-on-error: true

    #druid配置 监控 /druid/index.html
    druid:
      initial-size: 5
      max-active: 30
      min-idle: 10
      max-wait: 6000
      web-stat-filter.enabled: true
      stat-view-servlet.enabled: true
#禁用https-jsse-nio-9090-Poller
#  logging.level.org.apache.tomcat=INFO
logging:
  level:
    root: TRACE
    org:
      springframework:
        security: DEBUG
      apache:
        tomcat:
          util:
            net: WARN
  file:
    path: log/tacocloud.log
