spring:
  application:
    # 当前服务注册在Eureka Server的名称
    # 如果Consumer只是消费服务，可以不用注册到EurekaServer
    name: service-customer1
#  cloud:
#    config:
#      enabled: false
server:
  port: 8764
eureka:
  client:
    service-url:
      # 指定Eureka Server地址
      defaultZone: http://localhost:8761/eureka

