spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mookuu/kan/Spring/SpringCloudConfig.git
          search-paths: config-files
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka